---
env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-console: 0
  import/no-unresolved: 0